### PR TITLE
Added Exception Handling

### PR DESCRIPTION
**Pull request by yuktakodwani**

### CODE REVIEW

**Comment by yuktakodwani** [comment]
reviewed

**Review by yuktakodwani — COMMENTED** [review]
fine

**Review by yuktakodwani — COMMENTED** [review]
ok

**Review by yuktakodwani — COMMENTED** [review]
ok

**Review by yuktakodwani — COMMENTED** [review]
ok

**Comment by vijijay** [comment]
ok

**Review by vijijay — APPROVED** [review]

**Pull request merged**
